name: Node.js CI

on:
  push:
    branches: [ main, habilitando-pipeline ]
  pull_request:
    branches: [ main, habilitando-pipeline ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Run software tests
      run: npm run test-controller

    - name: Start API
      run: npm start &

    - name: Wait for API to start
      run: sleep 5

    - name: Run tests HTTP
      run: npm run test-external
